"""remove language from posts

Revision ID: 950a724b57da
Revises: b4f577bb4303
Create Date: 2020-11-07 18:16:49.121979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950a724b57da'
down_revision = 'b4f577bb4303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
